export type PaletteColor = { readonly name: string; readonly hex: string }

export const CLOTHING_PALETTE: ReadonlyArray<PaletteColor> = Object.freeze([
  { name: 'Black', hex: '#0a0a0a' },
  { name: 'Charcoal', hex: '#36454f' },
  { name: 'Gray', hex: '#808080' },
  { name: 'Silver', hex: '#c0c0c0' },
  { name: 'White', hex: '#fafafa' },
  { name: 'Cream', hex: '#f5e9d0' },
  { name: 'Beige', hex: '#d9c7a7' },
  { name: 'Tan', hex: '#c9a36a' },
  { name: 'Khaki', hex: '#b5a26b' },
  { name: 'Brown', hex: '#8b5a2b' },
  { name: 'Chocolate', hex: '#5b3a1e' },
  { name: 'Olive', hex: '#6a6a2a' },
  { name: 'Forest', hex: '#1f5132' },
  { name: 'Mint', hex: '#9bd4b2' },
  { name: 'Teal', hex: '#0a8d8d' },
  { name: 'Navy', hex: '#0b1f44' },
  { name: 'Royal', hex: '#1f3aa6' },
  { name: 'Denim', hex: '#3b5b8b' },
  { name: 'Sky', hex: '#7ec8e3' },
  { name: 'Lavender', hex: '#b497bd' },
  { name: 'Purple', hex: '#5a2a86' },
  { name: 'Magenta', hex: '#c2185b' },
  { name: 'Pink', hex: '#f48fb1' },
  { name: 'Coral', hex: '#ff7f6e' },
  { name: 'Red', hex: '#c92a2a' },
  { name: 'Burgundy', hex: '#7b1f2b' },
  { name: 'Maroon', hex: '#5a1a1a' },
  { name: 'Orange', hex: '#e87722' },
  { name: 'Mustard', hex: '#d4a13a' },
  { name: 'Yellow', hex: '#f2c200' },
  { name: 'Gold', hex: '#b8860b' },
])
