/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailSentRouteImport } from './routes/verify-email-sent'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PosRouteImport } from './routes/pos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SupplyIndexRouteImport } from './routes/supply/index'
import { Route as StoreIndexRouteImport } from './routes/store/index'
import { Route as ShopIndexRouteImport } from './routes/shop/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as ReportsIndexRouteImport } from './routes/reports/index'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as CustomersIndexRouteImport } from './routes/customers/index'
import { Route as UploadPhotoTokenRouteImport } from './routes/upload-photo.$token'
import { Route as SupplySuppliersRouteImport } from './routes/supply/suppliers'
import { Route as SupplyRouteIdRouteImport } from './routes/supply/$routeId'
import { Route as StoreRestockRequisitionsRouteImport } from './routes/store/restock-requisitions'
import { Route as StoreTransfersRouteImport } from './routes/store/transfers'
import { Route as StoreReceivingRouteImport } from './routes/store/receiving'
import { Route as StoreOpeningBalanceRouteImport } from './routes/store/opening-balance'
import { Route as ShopSalesRouteImport } from './routes/shop/sales'
import { Route as ShopOpeningBalanceRouteImport } from './routes/shop/opening-balance'
import { Route as SettingsUsersRouteImport } from './routes/settings/users'
import { Route as SettingsNotificationsRouteImport } from './routes/settings/notifications'
import { Route as SettingsShopsShopIdOverridesRouteImport } from './routes/settings/shops/$shopId/overrides'
import { Route as ShopShopIdRestockRouteImport } from './routes/shop/$shopId/restock'
import { Route as ReportsZRouteImport } from './routes/reports/z'
import { Route as ReportsXRouteImport } from './routes/reports/x'
import { Route as ReportsLedgerRouteImport } from './routes/reports/ledger'
import { Route as ProductsArticleNumberRouteImport } from './routes/products/$articleNumber'
import { Route as ReportsZIdRouteImport } from './routes/reports/z.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const VerifyEmailSentRoute = VerifyEmailSentRouteImport.update({
  id: '/verify-email-sent',
  path: '/verify-email-sent',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PosRoute = PosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplyIndexRoute = SupplyIndexRouteImport.update({
  id: '/supply/',
  path: '/supply/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreIndexRoute = StoreIndexRouteImport.update({
  id: '/store/',
  path: '/store/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIndexRoute = CustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadPhotoTokenRoute = UploadPhotoTokenRouteImport.update({
  id: '/upload-photo/$token',
  path: '/upload-photo/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplySuppliersRoute = SupplySuppliersRouteImport.update({
  id: '/supply/suppliers',
  path: '/supply/suppliers',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplyRouteIdRoute = SupplyRouteIdRouteImport.update({
  id: '/supply/$routeId',
  path: '/supply/$routeId',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRestockRequisitionsRoute = StoreRestockRequisitionsRouteImport.update({
  id: '/store/restock-requisitions',
  path: '/store/restock-requisitions',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreTransfersRoute = StoreTransfersRouteImport.update({
  id: '/store/transfers',
  path: '/store/transfers',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreReceivingRoute = StoreReceivingRouteImport.update({
  id: '/store/receiving',
  path: '/store/receiving',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreOpeningBalanceRoute = StoreOpeningBalanceRouteImport.update({
  id: '/store/opening-balance',
  path: '/store/opening-balance',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopSalesRoute = ShopSalesRouteImport.update({
  id: '/shop/sales',
  path: '/shop/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopOpeningBalanceRoute = ShopOpeningBalanceRouteImport.update({
  id: '/shop/opening-balance',
  path: '/shop/opening-balance',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsUsersRoute = SettingsUsersRouteImport.update({
  id: '/settings/users',
  path: '/settings/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsNotificationsRoute = SettingsNotificationsRouteImport.update({
  id: '/settings/notifications',
  path: '/settings/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsShopsShopIdOverridesRoute =
  SettingsShopsShopIdOverridesRouteImport.update({
    id: '/settings/shops/$shopId/overrides',
    path: '/settings/shops/$shopId/overrides',
    getParentRoute: () => rootRouteImport,
  } as any)
const ShopShopIdRestockRoute = ShopShopIdRestockRouteImport.update({
  id: '/shop/$shopId/restock',
  path: '/shop/$shopId/restock',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsZRoute = ReportsZRouteImport.update({
  id: '/reports/z',
  path: '/reports/z',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsXRoute = ReportsXRouteImport.update({
  id: '/reports/x',
  path: '/reports/x',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsLedgerRoute = ReportsLedgerRouteImport.update({
  id: '/reports/ledger',
  path: '/reports/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsArticleNumberRoute = ProductsArticleNumberRouteImport.update({
  id: '/products/$articleNumber',
  path: '/products/$articleNumber',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsZIdRoute = ReportsZIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ReportsZRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pos': typeof PosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email-sent': typeof VerifyEmailSentRoute
  '/products/$articleNumber': typeof ProductsArticleNumberRoute
  '/reports/ledger': typeof ReportsLedgerRoute
  '/reports/x': typeof ReportsXRoute
  '/reports/z': typeof ReportsZRouteWithChildren
  '/settings/users': typeof SettingsUsersRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/shops/$shopId/overrides': typeof SettingsShopsShopIdOverridesRoute
  '/shop/$shopId/restock': typeof ShopShopIdRestockRoute
  '/shop/opening-balance': typeof ShopOpeningBalanceRoute
  '/shop/sales': typeof ShopSalesRoute
  '/store/opening-balance': typeof StoreOpeningBalanceRoute
  '/store/receiving': typeof StoreReceivingRoute
  '/store/restock-requisitions': typeof StoreRestockRequisitionsRoute
  '/store/transfers': typeof StoreTransfersRoute
  '/supply/$routeId': typeof SupplyRouteIdRoute
  '/supply/suppliers': typeof SupplySuppliersRoute
  '/upload-photo/$token': typeof UploadPhotoTokenRoute
  '/customers/': typeof CustomersIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/store/': typeof StoreIndexRoute
  '/supply/': typeof SupplyIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/reports/z/$id': typeof ReportsZIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pos': typeof PosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email-sent': typeof VerifyEmailSentRoute
  '/products/$articleNumber': typeof ProductsArticleNumberRoute
  '/reports/ledger': typeof ReportsLedgerRoute
  '/reports/x': typeof ReportsXRoute
  '/reports/z': typeof ReportsZRouteWithChildren
  '/settings/users': typeof SettingsUsersRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/shops/$shopId/overrides': typeof SettingsShopsShopIdOverridesRoute
  '/shop/$shopId/restock': typeof ShopShopIdRestockRoute
  '/shop/opening-balance': typeof ShopOpeningBalanceRoute
  '/shop/sales': typeof ShopSalesRoute
  '/store/opening-balance': typeof StoreOpeningBalanceRoute
  '/store/receiving': typeof StoreReceivingRoute
  '/store/restock-requisitions': typeof StoreRestockRequisitionsRoute
  '/store/transfers': typeof StoreTransfersRoute
  '/supply/$routeId': typeof SupplyRouteIdRoute
  '/supply/suppliers': typeof SupplySuppliersRoute
  '/upload-photo/$token': typeof UploadPhotoTokenRoute
  '/customers': typeof CustomersIndexRoute
  '/products': typeof ProductsIndexRoute
  '/reports': typeof ReportsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/shop': typeof ShopIndexRoute
  '/store': typeof StoreIndexRoute
  '/supply': typeof SupplyIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/reports/z/$id': typeof ReportsZIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pos': typeof PosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email-sent': typeof VerifyEmailSentRoute
  '/products/$articleNumber': typeof ProductsArticleNumberRoute
  '/reports/ledger': typeof ReportsLedgerRoute
  '/reports/x': typeof ReportsXRoute
  '/reports/z': typeof ReportsZRouteWithChildren
  '/settings/users': typeof SettingsUsersRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/shops/$shopId/overrides': typeof SettingsShopsShopIdOverridesRoute
  '/shop/$shopId/restock': typeof ShopShopIdRestockRoute
  '/shop/opening-balance': typeof ShopOpeningBalanceRoute
  '/shop/sales': typeof ShopSalesRoute
  '/store/opening-balance': typeof StoreOpeningBalanceRoute
  '/store/receiving': typeof StoreReceivingRoute
  '/store/restock-requisitions': typeof StoreRestockRequisitionsRoute
  '/store/transfers': typeof StoreTransfersRoute
  '/supply/$routeId': typeof SupplyRouteIdRoute
  '/supply/suppliers': typeof SupplySuppliersRoute
  '/upload-photo/$token': typeof UploadPhotoTokenRoute
  '/customers/': typeof CustomersIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/store/': typeof StoreIndexRoute
  '/supply/': typeof SupplyIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/reports/z/$id': typeof ReportsZIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/forgot-password'
    | '/login'
    | '/pos'
    | '/reset-password'
    | '/verify-email-sent'
    | '/products/$articleNumber'
    | '/reports/ledger'
    | '/reports/x'
    | '/reports/z'
    | '/settings/users'
    | '/settings/notifications'
    | '/settings/shops/$shopId/overrides'
    | '/shop/$shopId/restock'
    | '/shop/opening-balance'
    | '/shop/sales'
    | '/store/opening-balance'
    | '/store/receiving'
    | '/store/restock-requisitions'
    | '/store/transfers'
    | '/supply/$routeId'
    | '/supply/suppliers'
    | '/upload-photo/$token'
    | '/customers/'
    | '/products/'
    | '/reports/'
    | '/settings/'
    | '/shop/'
    | '/store/'
    | '/supply/'
    | '/api/auth/$'
    | '/reports/z/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invite'
    | '/forgot-password'
    | '/login'
    | '/pos'
    | '/reset-password'
    | '/verify-email-sent'
    | '/products/$articleNumber'
    | '/reports/ledger'
    | '/reports/x'
    | '/reports/z'
    | '/settings/users'
    | '/settings/notifications'
    | '/settings/shops/$shopId/overrides'
    | '/shop/$shopId/restock'
    | '/shop/opening-balance'
    | '/shop/sales'
    | '/store/opening-balance'
    | '/store/receiving'
    | '/store/restock-requisitions'
    | '/store/transfers'
    | '/supply/$routeId'
    | '/supply/suppliers'
    | '/upload-photo/$token'
    | '/customers'
    | '/products'
    | '/reports'
    | '/settings'
    | '/shop'
    | '/store'
    | '/supply'
    | '/api/auth/$'
    | '/reports/z/$id'
  id:
    | '__root__'
    | '/'
    | '/accept-invite'
    | '/forgot-password'
    | '/login'
    | '/pos'
    | '/reset-password'
    | '/verify-email-sent'
    | '/products/$articleNumber'
    | '/reports/ledger'
    | '/reports/x'
    | '/reports/z'
    | '/settings/users'
    | '/settings/notifications'
    | '/settings/shops/$shopId/overrides'
    | '/shop/$shopId/restock'
    | '/shop/opening-balance'
    | '/shop/sales'
    | '/store/opening-balance'
    | '/store/receiving'
    | '/store/restock-requisitions'
    | '/store/transfers'
    | '/supply/$routeId'
    | '/supply/suppliers'
    | '/upload-photo/$token'
    | '/customers/'
    | '/products/'
    | '/reports/'
    | '/settings/'
    | '/shop/'
    | '/store/'
    | '/supply/'
    | '/api/auth/$'
    | '/reports/z/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcceptInviteRoute: typeof AcceptInviteRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PosRoute: typeof PosRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  VerifyEmailSentRoute: typeof VerifyEmailSentRoute
  ProductsArticleNumberRoute: typeof ProductsArticleNumberRoute
  ReportsLedgerRoute: typeof ReportsLedgerRoute
  ReportsXRoute: typeof ReportsXRoute
  ReportsZRoute: typeof ReportsZRouteWithChildren
  SettingsUsersRoute: typeof SettingsUsersRoute
  SettingsNotificationsRoute: typeof SettingsNotificationsRoute
  SettingsShopsShopIdOverridesRoute: typeof SettingsShopsShopIdOverridesRoute
  ShopShopIdRestockRoute: typeof ShopShopIdRestockRoute
  ShopOpeningBalanceRoute: typeof ShopOpeningBalanceRoute
  ShopSalesRoute: typeof ShopSalesRoute
  StoreOpeningBalanceRoute: typeof StoreOpeningBalanceRoute
  StoreReceivingRoute: typeof StoreReceivingRoute
  StoreRestockRequisitionsRoute: typeof StoreRestockRequisitionsRoute
  StoreTransfersRoute: typeof StoreTransfersRoute
  SupplyRouteIdRoute: typeof SupplyRouteIdRoute
  SupplySuppliersRoute: typeof SupplySuppliersRoute
  UploadPhotoTokenRoute: typeof UploadPhotoTokenRoute
  CustomersIndexRoute: typeof CustomersIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  ShopIndexRoute: typeof ShopIndexRoute
  StoreIndexRoute: typeof StoreIndexRoute
  SupplyIndexRoute: typeof SupplyIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email-sent': {
      id: '/verify-email-sent'
      path: '/verify-email-sent'
      fullPath: '/verify-email-sent'
      preLoaderRoute: typeof VerifyEmailSentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos': {
      id: '/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof PosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supply/': {
      id: '/supply/'
      path: '/supply'
      fullPath: '/supply/'
      preLoaderRoute: typeof SupplyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/': {
      id: '/store/'
      path: '/store'
      fullPath: '/store/'
      preLoaderRoute: typeof StoreIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/shop'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/': {
      id: '/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/': {
      id: '/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof CustomersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload-photo/$token': {
      id: '/upload-photo/$token'
      path: '/upload-photo/$token'
      fullPath: '/upload-photo/$token'
      preLoaderRoute: typeof UploadPhotoTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supply/suppliers': {
      id: '/supply/suppliers'
      path: '/supply/suppliers'
      fullPath: '/supply/suppliers'
      preLoaderRoute: typeof SupplySuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supply/$routeId': {
      id: '/supply/$routeId'
      path: '/supply/$routeId'
      fullPath: '/supply/$routeId'
      preLoaderRoute: typeof SupplyRouteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/restock-requisitions': {
      id: '/store/restock-requisitions'
      path: '/store/restock-requisitions'
      fullPath: '/store/restock-requisitions'
      preLoaderRoute: typeof StoreRestockRequisitionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/transfers': {
      id: '/store/transfers'
      path: '/store/transfers'
      fullPath: '/store/transfers'
      preLoaderRoute: typeof StoreTransfersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/receiving': {
      id: '/store/receiving'
      path: '/store/receiving'
      fullPath: '/store/receiving'
      preLoaderRoute: typeof StoreReceivingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/opening-balance': {
      id: '/store/opening-balance'
      path: '/store/opening-balance'
      fullPath: '/store/opening-balance'
      preLoaderRoute: typeof StoreOpeningBalanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/sales': {
      id: '/shop/sales'
      path: '/shop/sales'
      fullPath: '/shop/sales'
      preLoaderRoute: typeof ShopSalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/opening-balance': {
      id: '/shop/opening-balance'
      path: '/shop/opening-balance'
      fullPath: '/shop/opening-balance'
      preLoaderRoute: typeof ShopOpeningBalanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/users': {
      id: '/settings/users'
      path: '/settings/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof SettingsUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/notifications': {
      id: '/settings/notifications'
      path: '/settings/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof SettingsNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/shops/$shopId/overrides': {
      id: '/settings/shops/$shopId/overrides'
      path: '/settings/shops/$shopId/overrides'
      fullPath: '/settings/shops/$shopId/overrides'
      preLoaderRoute: typeof SettingsShopsShopIdOverridesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/z': {
      id: '/reports/z'
      path: '/reports/z'
      fullPath: '/reports/z'
      preLoaderRoute: typeof ReportsZRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/x': {
      id: '/reports/x'
      path: '/reports/x'
      fullPath: '/reports/x'
      preLoaderRoute: typeof ReportsXRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/ledger': {
      id: '/reports/ledger'
      path: '/reports/ledger'
      fullPath: '/reports/ledger'
      preLoaderRoute: typeof ReportsLedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$articleNumber': {
      id: '/products/$articleNumber'
      path: '/products/$articleNumber'
      fullPath: '/products/$articleNumber'
      preLoaderRoute: typeof ProductsArticleNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/z/$id': {
      id: '/reports/z/$id'
      path: '/$id'
      fullPath: '/reports/z/$id'
      preLoaderRoute: typeof ReportsZIdRouteImport
      parentRoute: typeof ReportsZRoute
    }
    '/settings/shops/$shopId/overrides': {
      id: '/settings/shops/$shopId/overrides'
      path: '/settings/shops/$shopId/overrides'
      fullPath: '/settings/shops/$shopId/overrides'
      preLoaderRoute: typeof SettingsShopsShopIdOverridesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$shopId/restock': {
      id: '/shop/$shopId/restock'
      path: '/shop/$shopId/restock'
      fullPath: '/shop/$shopId/restock'
      preLoaderRoute: typeof ShopShopIdRestockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ReportsZRouteChildren {
  ReportsZIdRoute: typeof ReportsZIdRoute
}

const ReportsZRouteChildren: ReportsZRouteChildren = {
  ReportsZIdRoute: ReportsZIdRoute,
}

const ReportsZRouteWithChildren = ReportsZRoute._addFileChildren(
  ReportsZRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcceptInviteRoute: AcceptInviteRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PosRoute: PosRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  VerifyEmailSentRoute: VerifyEmailSentRoute,
  ProductsArticleNumberRoute: ProductsArticleNumberRoute,
  ReportsLedgerRoute: ReportsLedgerRoute,
  ReportsXRoute: ReportsXRoute,
  ReportsZRoute: ReportsZRouteWithChildren,
  SettingsUsersRoute: SettingsUsersRoute,
  SettingsNotificationsRoute: SettingsNotificationsRoute,
  SettingsShopsShopIdOverridesRoute: SettingsShopsShopIdOverridesRoute,
  ShopShopIdRestockRoute: ShopShopIdRestockRoute,
  ShopOpeningBalanceRoute: ShopOpeningBalanceRoute,
  ShopSalesRoute: ShopSalesRoute,
  StoreOpeningBalanceRoute: StoreOpeningBalanceRoute,
  StoreReceivingRoute: StoreReceivingRoute,
  StoreRestockRequisitionsRoute: StoreRestockRequisitionsRoute,
  StoreTransfersRoute: StoreTransfersRoute,
  SupplyRouteIdRoute: SupplyRouteIdRoute,
  SupplySuppliersRoute: SupplySuppliersRoute,
  UploadPhotoTokenRoute: UploadPhotoTokenRoute,
  CustomersIndexRoute: CustomersIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  ReportsIndexRoute: ReportsIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  ShopIndexRoute: ShopIndexRoute,
  StoreIndexRoute: StoreIndexRoute,
  SupplyIndexRoute: SupplyIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
