/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SupplyIndexRouteImport } from './routes/supply/index'
import { Route as StoreIndexRouteImport } from './routes/store/index'
import { Route as ShopIndexRouteImport } from './routes/shop/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as ReportsIndexRouteImport } from './routes/reports/index'
import { Route as SupplySuppliersRouteImport } from './routes/supply/suppliers'
import { Route as SupplyRouteIdRouteImport } from './routes/supply/$routeId'
import { Route as StoreTransfersRouteImport } from './routes/store/transfers'
import { Route as StoreReceivingRouteImport } from './routes/store/receiving'
import { Route as ShopSalesRouteImport } from './routes/shop/sales'
import { Route as ReportsLedgerRouteImport } from './routes/reports/ledger'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplyIndexRoute = SupplyIndexRouteImport.update({
  id: '/supply/',
  path: '/supply/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreIndexRoute = StoreIndexRouteImport.update({
  id: '/store/',
  path: '/store/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplySuppliersRoute = SupplySuppliersRouteImport.update({
  id: '/supply/suppliers',
  path: '/supply/suppliers',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplyRouteIdRoute = SupplyRouteIdRouteImport.update({
  id: '/supply/$routeId',
  path: '/supply/$routeId',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreTransfersRoute = StoreTransfersRouteImport.update({
  id: '/store/transfers',
  path: '/store/transfers',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreReceivingRoute = StoreReceivingRouteImport.update({
  id: '/store/receiving',
  path: '/store/receiving',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopSalesRoute = ShopSalesRouteImport.update({
  id: '/shop/sales',
  path: '/shop/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsLedgerRoute = ReportsLedgerRouteImport.update({
  id: '/reports/ledger',
  path: '/reports/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/reports/ledger': typeof ReportsLedgerRoute
  '/shop/sales': typeof ShopSalesRoute
  '/store/receiving': typeof StoreReceivingRoute
  '/store/transfers': typeof StoreTransfersRoute
  '/supply/$routeId': typeof SupplyRouteIdRoute
  '/supply/suppliers': typeof SupplySuppliersRoute
  '/reports/': typeof ReportsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/store/': typeof StoreIndexRoute
  '/supply/': typeof SupplyIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/reports/ledger': typeof ReportsLedgerRoute
  '/shop/sales': typeof ShopSalesRoute
  '/store/receiving': typeof StoreReceivingRoute
  '/store/transfers': typeof StoreTransfersRoute
  '/supply/$routeId': typeof SupplyRouteIdRoute
  '/supply/suppliers': typeof SupplySuppliersRoute
  '/reports': typeof ReportsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/shop': typeof ShopIndexRoute
  '/store': typeof StoreIndexRoute
  '/supply': typeof SupplyIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/reports/ledger': typeof ReportsLedgerRoute
  '/shop/sales': typeof ShopSalesRoute
  '/store/receiving': typeof StoreReceivingRoute
  '/store/transfers': typeof StoreTransfersRoute
  '/supply/$routeId': typeof SupplyRouteIdRoute
  '/supply/suppliers': typeof SupplySuppliersRoute
  '/reports/': typeof ReportsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/store/': typeof StoreIndexRoute
  '/supply/': typeof SupplyIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/reports/ledger'
    | '/shop/sales'
    | '/store/receiving'
    | '/store/transfers'
    | '/supply/$routeId'
    | '/supply/suppliers'
    | '/reports/'
    | '/settings/'
    | '/shop/'
    | '/store/'
    | '/supply/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/reports/ledger'
    | '/shop/sales'
    | '/store/receiving'
    | '/store/transfers'
    | '/supply/$routeId'
    | '/supply/suppliers'
    | '/reports'
    | '/settings'
    | '/shop'
    | '/store'
    | '/supply'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/reports/ledger'
    | '/shop/sales'
    | '/store/receiving'
    | '/store/transfers'
    | '/supply/$routeId'
    | '/supply/suppliers'
    | '/reports/'
    | '/settings/'
    | '/shop/'
    | '/store/'
    | '/supply/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ReportsLedgerRoute: typeof ReportsLedgerRoute
  ShopSalesRoute: typeof ShopSalesRoute
  StoreReceivingRoute: typeof StoreReceivingRoute
  StoreTransfersRoute: typeof StoreTransfersRoute
  SupplyRouteIdRoute: typeof SupplyRouteIdRoute
  SupplySuppliersRoute: typeof SupplySuppliersRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  ShopIndexRoute: typeof ShopIndexRoute
  StoreIndexRoute: typeof StoreIndexRoute
  SupplyIndexRoute: typeof SupplyIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supply/': {
      id: '/supply/'
      path: '/supply'
      fullPath: '/supply/'
      preLoaderRoute: typeof SupplyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/': {
      id: '/store/'
      path: '/store'
      fullPath: '/store/'
      preLoaderRoute: typeof StoreIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/shop'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/': {
      id: '/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supply/suppliers': {
      id: '/supply/suppliers'
      path: '/supply/suppliers'
      fullPath: '/supply/suppliers'
      preLoaderRoute: typeof SupplySuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supply/$routeId': {
      id: '/supply/$routeId'
      path: '/supply/$routeId'
      fullPath: '/supply/$routeId'
      preLoaderRoute: typeof SupplyRouteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/transfers': {
      id: '/store/transfers'
      path: '/store/transfers'
      fullPath: '/store/transfers'
      preLoaderRoute: typeof StoreTransfersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/receiving': {
      id: '/store/receiving'
      path: '/store/receiving'
      fullPath: '/store/receiving'
      preLoaderRoute: typeof StoreReceivingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/sales': {
      id: '/shop/sales'
      path: '/shop/sales'
      fullPath: '/shop/sales'
      preLoaderRoute: typeof ShopSalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/ledger': {
      id: '/reports/ledger'
      path: '/reports/ledger'
      fullPath: '/reports/ledger'
      preLoaderRoute: typeof ReportsLedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ReportsLedgerRoute: ReportsLedgerRoute,
  ShopSalesRoute: ShopSalesRoute,
  StoreReceivingRoute: StoreReceivingRoute,
  StoreTransfersRoute: StoreTransfersRoute,
  SupplyRouteIdRoute: SupplyRouteIdRoute,
  SupplySuppliersRoute: SupplySuppliersRoute,
  ReportsIndexRoute: ReportsIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  ShopIndexRoute: ShopIndexRoute,
  StoreIndexRoute: StoreIndexRoute,
  SupplyIndexRoute: SupplyIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
