/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SupplyIndexRouteImport } from './routes/supply/index'
import { Route as StoreIndexRouteImport } from './routes/store/index'
import { Route as SupplySuppliersRouteImport } from './routes/supply/suppliers'
import { Route as SupplyRouteIdRouteImport } from './routes/supply/$routeId'
import { Route as StoreTransfersRouteImport } from './routes/store/transfers'
import { Route as StoreReceivingRouteImport } from './routes/store/receiving'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplyIndexRoute = SupplyIndexRouteImport.update({
  id: '/supply/',
  path: '/supply/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreIndexRoute = StoreIndexRouteImport.update({
  id: '/store/',
  path: '/store/',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplySuppliersRoute = SupplySuppliersRouteImport.update({
  id: '/supply/suppliers',
  path: '/supply/suppliers',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplyRouteIdRoute = SupplyRouteIdRouteImport.update({
  id: '/supply/$routeId',
  path: '/supply/$routeId',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreTransfersRoute = StoreTransfersRouteImport.update({
  id: '/store/transfers',
  path: '/store/transfers',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreReceivingRoute = StoreReceivingRouteImport.update({
  id: '/store/receiving',
  path: '/store/receiving',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/store/receiving': typeof StoreReceivingRoute
  '/store/transfers': typeof StoreTransfersRoute
  '/supply/$routeId': typeof SupplyRouteIdRoute
  '/supply/suppliers': typeof SupplySuppliersRoute
  '/store/': typeof StoreIndexRoute
  '/supply/': typeof SupplyIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/store/receiving': typeof StoreReceivingRoute
  '/store/transfers': typeof StoreTransfersRoute
  '/supply/$routeId': typeof SupplyRouteIdRoute
  '/supply/suppliers': typeof SupplySuppliersRoute
  '/store': typeof StoreIndexRoute
  '/supply': typeof SupplyIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/store/receiving': typeof StoreReceivingRoute
  '/store/transfers': typeof StoreTransfersRoute
  '/supply/$routeId': typeof SupplyRouteIdRoute
  '/supply/suppliers': typeof SupplySuppliersRoute
  '/store/': typeof StoreIndexRoute
  '/supply/': typeof SupplyIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/store/receiving'
    | '/store/transfers'
    | '/supply/$routeId'
    | '/supply/suppliers'
    | '/store/'
    | '/supply/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/store/receiving'
    | '/store/transfers'
    | '/supply/$routeId'
    | '/supply/suppliers'
    | '/store'
    | '/supply'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/store/receiving'
    | '/store/transfers'
    | '/supply/$routeId'
    | '/supply/suppliers'
    | '/store/'
    | '/supply/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StoreReceivingRoute: typeof StoreReceivingRoute
  StoreTransfersRoute: typeof StoreTransfersRoute
  SupplyRouteIdRoute: typeof SupplyRouteIdRoute
  SupplySuppliersRoute: typeof SupplySuppliersRoute
  StoreIndexRoute: typeof StoreIndexRoute
  SupplyIndexRoute: typeof SupplyIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supply/': {
      id: '/supply/'
      path: '/supply'
      fullPath: '/supply/'
      preLoaderRoute: typeof SupplyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/': {
      id: '/store/'
      path: '/store'
      fullPath: '/store/'
      preLoaderRoute: typeof StoreIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supply/suppliers': {
      id: '/supply/suppliers'
      path: '/supply/suppliers'
      fullPath: '/supply/suppliers'
      preLoaderRoute: typeof SupplySuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supply/$routeId': {
      id: '/supply/$routeId'
      path: '/supply/$routeId'
      fullPath: '/supply/$routeId'
      preLoaderRoute: typeof SupplyRouteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/transfers': {
      id: '/store/transfers'
      path: '/store/transfers'
      fullPath: '/store/transfers'
      preLoaderRoute: typeof StoreTransfersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/receiving': {
      id: '/store/receiving'
      path: '/store/receiving'
      fullPath: '/store/receiving'
      preLoaderRoute: typeof StoreReceivingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StoreReceivingRoute: StoreReceivingRoute,
  StoreTransfersRoute: StoreTransfersRoute,
  SupplyRouteIdRoute: SupplyRouteIdRoute,
  SupplySuppliersRoute: SupplySuppliersRoute,
  StoreIndexRoute: StoreIndexRoute,
  SupplyIndexRoute: SupplyIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
